from pathlib import Path
ROOT=Path(__file__).resolve().parent
MODULE='  /* STICKY TOOL CONTROLS */\n  R.isToolToolbarPage=()=>[\'slider\',\'pyramid\',\'wordparts\',\'lettertiles\'].includes(document.body.dataset.page);\n  R.toolToolbarLabels={"reading-edit": "Edit", "reading-copy": "Copy link", "reading-previous": "Previous", "reading-next": "Next", "example-previous": "Previous example", "example-next": "Next example", "tiles-edit": "Edit", "tiles-copy": "Copy link", "complete-return": "Done", "timer-start": "Start", "timer-pause": "Pause", "timer-reset": "Reset"};\n  R.scheduleToolToolbar=()=>{if(!R.toolToolbar||R.toolToolbarFrame)return;R.toolToolbarFrame=requestAnimationFrame(()=>{R.toolToolbarFrame=null;R.refreshToolToolbar();});};\n  R.refreshToolToolbar=()=>{\n    const footer=R.toolToolbar;if(!footer)return;\n    const visible=element=>{for(let node=element;node&&node!==footer;node=node.parentElement)if(node.hidden)return false;return true;};\n    const groups=Array.from(footer.querySelectorAll(\'.tool-toolbar-group\'));\n    groups.forEach(group=>{\n      group.hidden=false;\n      if(group.dataset.toolControls===\'spelling\'&&R.$(\'#reader-panel\').hidden){group.hidden=true;return;}\n      group.hidden=!Array.from(group.querySelectorAll(\'button,a,output,.nav-count\')).some(visible);\n    });\n    const active=groups.some(group=>!group.hidden);footer.hidden=!active;\n    const height=active?Math.ceil(footer.getBoundingClientRect().height):0;\n    if(R.toolToolbarHeight!==height){R.toolToolbarHeight=height;document.documentElement.style.setProperty(\'--tool-toolbar-height\',height+\'px\');window.dispatchEvent(new Event(\'reading:layout\'));}\n  };\n  R.initToolToolbar=()=>{\n    if(!R.isToolToolbarPage()||R.toolToolbar)return;\n    const bar=R.$(\'#appbar\'),footer=document.createElement(\'nav\');footer.id=\'tool-toolbar\';footer.className=\'tool-toolbar\';footer.setAttribute(\'aria-label\',\'Activity controls\');footer.hidden=true;\n    const inner=document.createElement(\'div\');inner.className=\'tool-toolbar-inner\';footer.appendChild(inner);\n    for(const slot of [\'actions\',\'reading\',\'timer\']){const group=bar.querySelector(\'[data-nav-slot="\'+slot+\'"]\');if(group){group.classList.add(\'tool-toolbar-group\');inner.appendChild(group);}}\n    if(document.body.dataset.page===\'lettertiles\'){const spelling=R.$(\'.tile-actions\');if(spelling){spelling.classList.add(\'tool-toolbar-group\');spelling.dataset.toolControls=\'spelling\';inner.appendChild(spelling);}}\n    document.body.appendChild(footer);document.body.classList.add(\'has-tool-toolbar\');R.toolToolbar=footer;\n    if(typeof ResizeObserver===\'function\')new ResizeObserver(()=>R.scheduleToolToolbar()).observe(footer);\n    window.addEventListener(\'resize\',()=>R.scheduleToolToolbar());\n    R.refreshToolToolbar();\n  };\n'
STYLES='/* STICKY TOOL CONTROLS */\n#tool-toolbar { position:fixed; bottom:0; left:0; right:0; z-index:950; background:#fff; color:#552CB8; border-top:1px solid #e5deef; box-shadow:0 -4px 18px #25194f0d; padding:10px 16px calc(10px + env(safe-area-inset-bottom,0px)); }\n#tool-toolbar[hidden],#tool-toolbar [hidden] { display:none !important; }\n#tool-toolbar .tool-toolbar-inner { display:flex; align-items:center; justify-content:flex-start; gap:12px; width:100%; max-width:1200px; margin:0 auto; overflow-x:auto; overscroll-behavior-x:contain; scrollbar-width:thin; }\n#tool-toolbar .tool-toolbar-group { display:flex; flex:0 0 auto; align-items:center; gap:8px; margin:0; padding:0; }\n#tool-toolbar .icon-button { display:inline-flex; align-items:center; justify-content:center; flex:0 0 auto; gap:7px; width:auto; min-width:44px; min-height:44px; padding:8px 12px; background:#fff; color:#552CB8; border:1px solid #552CB8; white-space:nowrap; }\n#tool-toolbar .icon-button:hover:not(:disabled) { background:#f5f1ff; color:#552CB8; }\n#tool-toolbar .nav-icon { width:20px; height:20px; flex:0 0 auto; }\n#tool-toolbar .tool-toolbar-label,#tool-toolbar .creator-add-button span { font-size:13px; font-weight:700; line-height:1.3; color:inherit; }\n#tool-toolbar .nav-count,#tool-toolbar .timer-value { color:#552CB8; background:#fff; white-space:nowrap; }\n#tool-toolbar .timer-value { min-width:62px; font-variant-numeric:tabular-nums; }\n#tool-toolbar .btn { min-height:44px; margin:0; white-space:nowrap; }\n#tool-toolbar :is(button,a):focus-visible { outline:2px solid #552CB8; outline-offset:2px; }\nbody.has-tool-toolbar #reader-panel { bottom:var(--tool-toolbar-height,0px); }\nbody.has-tool-toolbar .page-content { padding-bottom:calc(var(--tool-toolbar-height,0px) + 50px); }\nbody.has-tool-toolbar { scroll-padding-bottom:calc(var(--tool-toolbar-height,0px) + 20px); }\n@media(max-width:576px) { #tool-toolbar { padding:8px 10px calc(8px + env(safe-area-inset-bottom,0px)); } }\n'
paths=['assets/js/app.js','assets/js/language/reading.js','assets/css/styles.css']
for name in paths:
    if not (ROOT/name).exists():raise SystemExit('Missing '+name+'. Extract into the current Language-layout repository root. No files changed.')
original={name:(ROOT/name).read_text(encoding='utf-8') for name in paths}
app=original['assets/js/app.js']
if '/* STICKY TOOL CONTROLS */' in app:raise SystemExit('Sticky tool controls are already installed. No files changed.')
if 'R.finishWhiteHeader' not in app:raise SystemExit('Expected the current white-header/Lesson Plan toolbar update. No files changed.')
def once(text,old,new,name):
    if text.count(old)!=1:raise SystemExit('Unexpected source anchor in '+name+'. No files changed.')
    return text.replace(old,new,1)
app=once(app,'  R.init = () => {',MODULE+'  R.init = () => {','app initializer')
app=once(app,'el.innerHTML=R.icon(icon);',"el.innerHTML=R.icon(icon);if(R.isToolToolbarPage()&&id!=='creator-add-to-lesson'){const caption=document.createElement('span');caption.className='tool-toolbar-label';caption.textContent=R.toolToolbarLabels[id]||label;el.appendChild(caption);}",'tool action labels')
app=once(app,'document.querySelector(`[data-nav-slot="${slot}"]`).appendChild(el);return el;','document.querySelector(`[data-nav-slot="${slot}"]`).appendChild(el);R.scheduleToolToolbar();return el;','action refresh hook')
app=once(app,'el.hidden=!visible;el.disabled=disabled;','const footerVisibilityChanged=el.hidden!==!visible;el.hidden=!visible;el.disabled=disabled;if(footerVisibilityChanged)R.scheduleToolToolbar();','visibility hook')
app=once(app,'    R.finishWhiteHeader();','    R.finishWhiteHeader();\n    R.initToolToolbar();','toolbar initialization')
reader=original['assets/js/language/reading.js']
reader=once(reader,'resize=setTimeout(()=>this.build(true),100);','resize=setTimeout(()=>{const retainFocus=this.stage.contains(document.activeElement),resumeAdvance=this.timer!==null&&!this.busy&&this.rows[this.rowIndex]?.complete;this.build(true);if(resumeAdvance)this.progress(true);if(retainFocus)this.focus();},100);','reader layout focus')
updates={'assets/js/app.js':app,'assets/js/language/reading.js':reader,'assets/css/styles.css':original['assets/css/styles.css'].rstrip()+'\n\n'+STYLES}
backup=ROOT.parent/(ROOT.name+'-sticky-tool-controls-backup')
for name in updates:
    path=backup/name;path.parent.mkdir(parents=True,exist_ok=True)
    if not path.exists():path.write_text(original[name],encoding='utf-8')
for name,text in updates.items():(ROOT/name).write_text(text,encoding='utf-8');print('Updated',name)
print('Activity controls now use bottom toolbars; top navigation and Lesson Plan toolbar are preserved.')
print('Original files backed up outside the repository:',backup)
